name: Crate CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
jobs:
  publish-crate:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - name: Install nightly Rust
      - run: rustup update nightly
      - name: set nightly Rust default
      - run: rustup default nightly
      - uses: actions/checkout@v4
      - name: build the package
        run: cd tiny_prng && cargo build --release
      - name: publish the package
        run: cargo publish --token=${{ secrets.CRATESIO_CD_TOKEN }}
