name: Wasm CI/CD

on:
  push:
    branches:
      - main
      - "fix/**"
      - "feat/**"
jobs:
  build-npm-package:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - name: Install nightly Rust
        run: rustup update nightly
      - name: set nightly Rust default
        run: rustup default nightly
      - name: Install wasm-pack
        run: sh -c "curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh"
      - name: build package
        run: cd wasm_web && make clean && make build