name: Wasm CI/CD

on:
  push:
    branches:
      - main
      - "fix/**"
      - "feat/**"
jobs:
  build-and-publish-npm-package:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - name: Install nightly Rust
        run: rustup update nightly
      - name: set nightly Rust default
        run: rustup default nightly
      - name: Generate code coverage
        run: sh -c "curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh"
      - name: build package
        run: cd wasm_web && wasm-pack build && wasm-pack pack
      - name: Display Tag Information
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "Triggered by tag: ${{ github.ref_name }}"
          echo "On main branch: ${{ github.ref == 'refs/heads/main' }}"
      - name: publish the package
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo //registry.npmjs.com/:_authToken=${{ secrets.NPM_CD_TOKEN }} > ~/.npmrc && npm publish
