name: Publish npm package

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
jobs:
  build-npm-package:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - name: Display Tag Information
        run: |
          echo "Triggered by tag: ${{ github.ref_name }}"
          echo "On main branch: ${{ github.ref == 'refs/heads/main' }}"
      - name: Install nightly Rust
        run: rustup update nightly
      - name: set nightly Rust default
        run: rustup default nightly
      - name: add wasm32-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown
      - name: install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli
      - name: build and publish the package
        run: |
          set -e
          echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_CD_TOKEN }} > ~/.npmrc
          cd wasm_web
          make build
          cd pkg
          npm pack
          npm publish